version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    networks:
      proxy_net:
        ipv4_address: 172.21.0.2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    networks:
      proxy_net:
        ipv4_address: 172.21.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: always
    environment:
      - WG_HOST=w${DOMAIN}
      - PASSWORD_HASH=${WIREGUARD_PASSWORDHASH}
      - VIRTUAL_PORT=51821
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - WG_DEFAULT_DNS=172.21.0.4
    ports:
      - "51820:51820/udp" 
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg-easy/config:/etc/wireguard
    networks:
      proxy_net:
        ipv4_address: 172.21.0.5

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      proxy_net:
        ipv4_address: 172.21.0.4
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - "53:53/tcp"        # DNS TCP
      - "53:53/udp"        # DNS UDP
      - "67:67/udp"        # DHCP
      - "8080:80/tcp"      # Interfaz web de Pi-hole movida a puerto 8080

networks:
  proxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
